[package]
name = "react_rust_wasm"
version = "1.0.0"
authors = ["me"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.23"
fujisaki_ringsig = "0.0.3"
hex = "0.3.2"
serde = "1.0.79"
serde_json = "1.0.31"
js-sys = "0.3.0"

[dev-dependencies]
#wasm-bindgen-test = "=0.2.23"